offload_optimizer:
  device: none
  pin_memory: true
offload_param:
  device: none
  pin_memory: true
overlap_comm: true
contiguous_gradients: true
sub_group_size: 1000000000
reduce_bucket_size: auto
stage3_prefetch_bucket_size: auto
stage3_param_persistence_threshold: auto
stage3_max_live_parameters: 1000000000
stage3_max_reuse_distance: 1000000000
stage3_gather_16bit_weights_on_model_save: true
max_split_size_mb: 128